import type { Department, Product } from './src/types/product';

// Departamentos más comunes de supermercado
export const departments: Department[] = [
  {
    id: 1,
    name: 'Frutas y Verduras',
    description: 'Productos frescos, frutas y vegetales orgánicos',
    icon: '🥕',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'frutas-verduras',
    isActive: true,
  },
  {
    id: 2,
    name: 'Carnes, Pescados y Mariscos',
    description: 'Carnes frescas, embutidos y mariscos',
    icon: '🥩',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'carnes-pescados',
    isActive: true,
  },
  {
    id: 3,
    name: 'Lácteos y Huevos',
    description: 'Leche, quesos, yogures y productos Lácteos',
    icon: '🥛',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'lacteos-huevos',
    isActive: true,
  },
  {
    id: 4,
    name: 'Panadeía y Tortillería',
    description: 'Pan fresco, pasteles, productos horneados y tortillas',
    icon: '🍞',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'panaderia-y-tortilleria',
    isActive: true,
  },
  {
    id: 5,
    name: 'Congelados',
    description: 'Productos congelados y helados',
    icon: '🧊',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'congelados',
    isActive: true,
  },
  {
    id: 6,
    name: 'Despensa',
    description: 'Productos no perecederos, enlatados y granos',
    icon: '🥫',
    slug: 'despensa',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    isActive: true,
  },
  {
    id: 7,
    name: 'Bebidas y Licores',
    description: 'Refrescos, jugos, agua y bebidas alcohólicas',
    icon: '🥤',
    slug: 'bebidas',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    isActive: true,
  },
  {
    id: 8,
    name: 'Limpieza',
    description: 'Productos de limpieza para el hogar',
    icon: '🧽',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'limpieza',
    isActive: true,
  },
  {
    id: 9,
    name: 'Cuidado Personal',
    description: 'Higiene personal, cosm�ticos y farmacia',
    icon: '🧴',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'cuidado-personal',
    isActive: true,
  },
  {
    id: 10,
    name: 'Bebés',
    description: 'Productos para bebés y niños pequeños',
    icon: '👶',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'bebe',
    isActive: true,
  },
  {
    id: 11,
    name: 'Mascotas',
    description: 'Alimento y accesorios para mascotas',
    icon: '🐕',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'mascotas',
    isActive: true,
  },
  {
    id: 12,
    name: 'Hogar',
    description: 'Artículos para el hogar y decoración',
    icon: '🏠',
    image: 'https://placehold.co/600x600/22c55e/f97316/png',
    slug: 'hogar',
    isActive: true,
  },
];

// Productos de ejemplo
export const products: Product[] = [
  // Frutas y Verduras
  {
    id: 1,
    sku: 'FRU001',
    slug: 'manzanas-rojas',
    name: 'Manzanas Rojas',
    description: 'Manzanas rojas frescas y crujientes',
    price: 25.5,
    originalPrice: 30.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🍎'],
    category: { id: 1, name: 'Frutas', slug: 'frutas', isActive: true },
    departmentId: 1,
    brand: 'Frutas Premium',
    unit: 'kg',
    stock: 50,
    weight: 1000,
    dimensions: { length: 10, width: 8, height: 8 },
    isOnSale: true,
    discount: 15,
    rating: 4.5,
    reviews: 124,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 2,
    sku: 'VER001',
    slug: 'zanahorias-organicas',
    name: 'Zanahorias',
    description: 'Zanahorias frescas orgánicas',
    price: 18.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🥕'],
    category: { id: 2, name: 'Verduras', slug: 'verduras', isActive: true },
    departmentId: 1,
    brand: 'Orgánicos del Campo',
    unit: 'kg',
    stock: 75,
    weight: 1000,
    dimensions: { length: 20, width: 3, height: 3 },
    isOnSale: false,
    rating: 4.8,
    reviews: 89,
    isActive: true,
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-10T00:00:00Z',
  },
  {
    id: 3,
    sku: 'FRU003',
    slug: 'aguacates-hass',
    name: 'Aguacates Hass',
    description: 'Aguacates Hass maduros y cremosos',
    price: 45.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🥑'],
    category: { id: 1, name: 'Frutas', slug: 'frutas', isActive: true },
    departmentId: 1,
    brand: 'Frutas Premium',
    unit: 'kg',
    stock: 30,
    weight: 200,
    dimensions: { length: 8, width: 6, height: 6 },
    isOnSale: false,
    rating: 4.7,
    reviews: 156,
    isActive: true,
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-12T00:00:00Z',
  },
  // Carnes, Pescados y Mariscos
  {
    id: 4,
    sku: 'CAR001',
    slug: 'pechuga-de-pollo',
    name: 'Pechuga de Pollo',
    description: 'Pechuga de pollo sin hueso y sin piel',
    price: 120.0,
    originalPrice: 135.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🍗'],
    category: { id: 3, name: 'Carnes', slug: 'carnes', isActive: true },
    departmentId: 2,
    brand: 'Carnes Selectas',
    unit: 'kg',
    stock: 25,
    weight: 1000,
    dimensions: { length: 25, width: 15, height: 3 },
    isOnSale: true,
    discount: 11,
    rating: 4.6,
    reviews: 67,
    isActive: true,
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-14T00:00:00Z',
  },
  {
    id: 5,
    sku: 'PES001',
    slug: 'salmon-fresco',
    name: 'Salmón Fresco',
    description: 'Filete de salmón fresco del Atlántico',
    price: 280.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🐟'],
    category: { id: 4, name: 'Pescados', slug: 'pescados', isActive: true },
    departmentId: 2,
    brand: 'Mariscos del Mar',
    unit: 'kg',
    stock: 15,
    weight: 1000,
    dimensions: { length: 30, width: 12, height: 4 },
    isOnSale: false,
    rating: 4.9,
    reviews: 43,
    isActive: true,
    createdAt: '2024-01-04T00:00:00Z',
    updatedAt: '2024-01-16T00:00:00Z',
  },
  // Lácteos y Huevos
  {
    id: 6,
    sku: 'LAC001',
    slug: 'leche-entera',
    name: 'Leche Entera',
    description: 'Leche entera pasteurizada 1L',
    price: 22.5,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🥛'],
    category: { id: 5, name: 'Lácteos', slug: 'lacteos', isActive: true },
    departmentId: 3,
    brand: 'Lácteos La Vaca',
    unit: 'L',
    stock: 100,
    weight: 1030,
    dimensions: { length: 7, width: 7, height: 23 },
    isOnSale: false,
    rating: 4.4,
    reviews: 203,
    isActive: true,
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: 7,
    sku: 'HUE001',
    slug: 'huevos-blancos',
    name: 'Huevos Blancos',
    description: 'Cartón de 12 huevos blancos frescos',
    price: 35.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🥚'],
    category: { id: 6, name: 'Huevos', slug: 'huevos', isActive: true },
    departmentId: 3,
    brand: 'Granja San José',
    unit: 'cartón',
    stock: 80,
    weight: 720,
    dimensions: { length: 29, width: 11, height: 6 },
    isOnSale: false,
    rating: 4.7,
    reviews: 145,
    isActive: true,
    createdAt: '2024-01-06T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  // Panadería
  {
    id: 8,
    sku: 'PAN001',
    slug: 'pan-integral',
    name: 'Pan Integral',
    description: 'Pan integral de granos enteros',
    price: 28.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🍞'],
    category: { id: 7, name: 'Pan', slug: 'pan', isActive: true },
    departmentId: 4,
    brand: 'Panadería Artesanal',
    unit: 'pieza',
    stock: 40,
    weight: 680,
    dimensions: { length: 25, width: 12, height: 8 },
    isOnSale: false,
    rating: 4.3,
    reviews: 78,
    isActive: true,
    createdAt: '2024-01-07T00:00:00Z',
    updatedAt: '2024-01-22T00:00:00Z',
  },
  // Congelados
  {
    id: 9,
    sku: 'CON001',
    slug: 'pizza-margarita-congelada',
    name: 'Pizza Margarita Congelada',
    description: 'Pizza margarita congelada familiar',
    price: 85.0,
    originalPrice: 95.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🍕'],
    category: { id: 8, name: 'Comida Congelada', slug: 'comida-congelada', isActive: true },
    departmentId: 5,
    brand: 'Congelados Premium',
    unit: 'pieza',
    stock: 60,
    weight: 450,
    dimensions: { length: 31, width: 31, height: 3 },
    isOnSale: true,
    discount: 10,
    rating: 4.2,
    reviews: 92,
    isActive: true,
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-24T00:00:00Z',
  },
  // Despensa
  {
    id: 10,
    sku: 'GRA001',
    slug: 'arroz-blanco',
    name: 'Arroz Blanco',
    description: 'Arroz blanco de grano largo 1kg',
    price: 18.5,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🍚'],
    category: { id: 9, name: 'Granos', slug: 'granos', isActive: true },
    departmentId: 6,
    brand: 'Granos del Campo',
    unit: 'kg',
    stock: 120,
    weight: 1000,
    dimensions: { length: 18, width: 26, height: 4 },
    isOnSale: false,
    rating: 4.5,
    reviews: 167,
    isActive: true,
    createdAt: '2024-01-09T00:00:00Z',
    updatedAt: '2024-01-26T00:00:00Z',
  },
  // Bebidas
  {
    id: 11,
    sku: 'AGU001',
    slug: 'agua-natural',
    name: 'Agua Natural',
    description: 'Agua purificada natural 1.5L',
    price: 12.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=💧'],
    category: { id: 10, name: 'Agua', slug: 'agua', isActive: true },
    departmentId: 7,
    brand: 'Agua Pura',
    unit: 'botella',
    stock: 200,
    weight: 1500,
    dimensions: { length: 8, width: 8, height: 32 },
    isOnSale: false,
    rating: 4.6,
    reviews: 234,
    isActive: true,
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-28T00:00:00Z',
  },
  // Limpieza
  {
    id: 12,
    sku: 'DET001',
    slug: 'detergente-liquido',
    name: 'Detergente Líquido',
    description: 'Detergente líquido para ropa 1L',
    price: 45.0,
    images: ['https://placehold.co/300x300/22c55e/ffffff/png?text=🧽'],
    category: { id: 11, name: 'Detergentes', slug: 'detergentes', isActive: true },
    departmentId: 8,
    brand: 'Limpia Todo',
    unit: 'L',
    stock: 85,
    weight: 1050,
    dimensions: { length: 8, width: 8, height: 25 },
    isOnSale: false,
    rating: 4.4,
    reviews: 112,
    isActive: true,
    createdAt: '2024-01-11T00:00:00Z',
    updatedAt: '2024-01-30T00:00:00Z',
  },
];
